name: Run from other event
on:
  repository_dispatch:
    types: [scan_image]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get latest artifact
        id: get-artifact
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_PAT }}
          result-encoding: string
          script: |
            const repoOwner = 'piraces';
            const repoName = 'docker-repo-actions';
            const workflowId = 'docker-image.yml';
            
            // Get the latest workflow run
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: repoOwner,
              repo: repoName,
              workflow_id: workflowId,
              per_page: 1,
            });
            const latestRun = runs.workflow_runs[0];
            console.log(latestRun);
            
            // Get the artifact
            const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: repoOwner,
              repo: repoName,
              run_id: latestRun.id,
            });
            const artifact = artifacts.artifacts[0];
            console.log(artifact);
            
            // Get the download URL and set it as output
            const downloadUrl = artifact.archive_download_url;
            return downloadUrl;

      - name: Get result
        run: echo "${{steps.get-artifact.outputs.result}}"
        
      - name: Download and extract artifact
        run: |
          curl -L -o artifact.zip "${{ steps.get-artifact.outputs.result }}"
          unzip artifact.zip
          ls -la

      - name: Build an image from Dockerfile
        run: |
          docker build -t test:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      
